version: 1.0.{build}
image:
- Visual Studio 2017
install:
- ps: Install-Module Pester -Force -Scope CurrentUser
build: off
skip_commits:
  files:
    -README.md
    
branches:
  only:
    - master
    - dev

test_script:
- ps: Invoke-Pester -EnableExit
